"""统一的工具和 Agent 错误码。"""

ERROR_CLI_ARGUMENTS = "cli_arguments_error"
ERROR_INVALID_AGENT_ACTION = "invalid_agent_action"
ERROR_INVALID_ARGUMENTS = "invalid_arguments"
ERROR_INVALID_FINAL_ANSWER = "invalid_final_answer"
ERROR_INVALID_TOOL_ARGUMENTS = "invalid_tool_arguments"
ERROR_INVALID_TOOL_NAME = "invalid_tool_name"
ERROR_INVALID_TOOL_SCHEMA = "invalid_tool_schema"
ERROR_PLANNER_INVALID_JSON = "planner_invalid_json"
ERROR_PLANNER = "planner_error"
ERROR_TOOL = "tool_error"
ERROR_TOOL_EXCEPTION = "tool_exception"
ERROR_TOOL_REQUIRES_CONFIRMATION = "tool_requires_confirmation"
ERROR_UNKNOWN_TOOL = "unknown_tool"
